name: Trigger Main Repo Sync

on:
  push:
    branches:
      - main

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger main repository update
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/TWOJA-ORGANIZACJA/GLOWNE-REPO/dispatches \
            -d "{
              \"event_type\": \"submodule-main-updated\",
              \"client_payload\": {
                \"submodule\": \"$REPO_NAME\",
                \"commit\": \"$GITHUB_SHA\"
              }
            }"
